# Generated by Django 3.1.2 on 2020-10-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='max',
        ),
        migrations.RemoveField(
            model_name='flowers',
            name='min',
        ),
        migrations.AddField(
            model_name='flowers',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowers',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
