# Generated by Django 3.1.2 on 2020-10-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_auto_20201027_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowers',
            old_name='max_length',
            new_name='max',
        ),
        migrations.RemoveField(
            model_name='flowers',
            name='min_length',
        ),
    ]
