# Generated by Django 3.1.3 on 2020-11-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_auto_20201031_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='FlowersImage',
        ),
    ]
