# Generated by Django 3.1.3 on 2020-11-11 14:02

import applications.shrubs.models.image
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shrubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('species', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShrubsImage',
            fields=[
                ('shrubs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shrubs.shrubs')),
                ('original', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=applications.shrubs.models.image.upload_to)),
            ],
        ),
    ]
