# Generated by Django 3.1.3 on 2020-11-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treesimage',
            old_name='shrubs',
            new_name='trees',
        ),
    ]
